module.exports = {
    bibleBooks: {
        Gn: "Gênesis",
        Ex: "Êxodo",
        Lv: "Levítico",
        Nm: "Números",
        Dt: "Deuteronômio",
        Js: "Josué",
        Jz: "Juízes",
        Rt: "Rute",
        "1 Sm": "1o. Livro de Samuel",
        "2 Sm": "2o. Livro de Samuel",
        "1 Rs": "1o. Livro de Reis",
        "2 Rs": "2o. Livro de Reis",
        "1 Cr": "1o. Livro de Crônicas",
        "2 Cr": "2o. Livro de Crônicas",
        Ed: "Esdras",
        Ne: "Neemias",
        Et: "Ester",
        Jó: "Jó",
        Sl: "Salmos",
        Pv: "Provérbios ",
        Ec: "Eclesiastes",
        Ct: "Cântico dos Cânticos",
        Is: "Isaías",
        Jr: "Jeremias",
        Lm: "Lamentações de Jeremias",
        Ez: "Ezequiel",
        Dn: "Daniel",
        Os: "Oséias",
        Jl: "Joel",
        Am: "Amós",
        Ob: "Obadias",
        Jn: "Jonas",
        Mq: "Miquéias",
        Na: "Naum",
        Hc: "Habacuque",
        Sf: "Sofonias",
        Ag: "Ageu",
        Zc: "Zacarias",
        Ml: "Malaquias",
        Mt: "Mateus",
        Mc: "Marcos",
        Lc: "Lucas",
        Jo: "João",
        At: "Atos dos Apóstolos",
        Rm: "Romanos",
        "1 Co": "1a. Carta aos Coríntios",
        "2 Co": "2a. Carta aos Coríntios",
        Gl: "Gálatas",
        Ef: "Efésios",
        Fp: "Filipenses",
        Cl: "Colossenses",
        "1 Ts": "1a. Carta aos Tessalonicenses",
        "2 Ts": "2a. Carta aos Tessalonicenses",
        "1 Tm": "1a. Carta a Timóteo",
        "2 Tm": "2a. Carta a Timóteo",
        Tt: "Tito",
        Fm: "Filemon",
        Hb: "Hebreus",
        Tg: "Tiago",
        "1 Pe": "1a. Carta de Pedro",
        "2 Pe": "2a. Carta de Pedro",
        "1 Jo": "1a. Carta de João",
        "2 Jo": "2a. Carta de João",
        "3 Jo": "3a. Carta de João",
        Jd: "Judas",
        Ap: "Apocalipse"
    }
};
